import { Transaction, DailyClosing, EmployeeCommission, Voucher, AccountingExport } from "./types";
import { format, subDays } from "date-fns";

// Helper to generate dates relative to today
const today = new Date();
const d = (daysAgo: number, time: string = "12:00:00") => {
  const date = subDays(today, daysAgo);
  return `${format(date, "yyyy-MM-dd")}T${time}`;
};
const dd = (daysAgo: number) => format(subDays(today, daysAgo), "yyyy-MM-dd");

export const mockTransactions: Transaction[] = [
  {
    id: "t1",
    salonId: "demo",
    dateTime: d(0, "09:30:00"),
    clientId: "c1",
    clientName: "Anna Kowalska",
    staffId: "s1",
    staffName: "Maria Kowalczyk",
    locationId: null,
    itemType: "usługa",
    itemCategory: "Twarz",
    itemName: "Mezoterapia twarzy",
    quantity: 1,
    unitPriceBrutto: 350,
    discountAmount: 0,
    vatRate: 23,
    netAmount: 284.55,
    vatAmount: 65.45,
    grossAmount: 350,
    paymentMethod: "karta",
    tipAmount: 30,
    relatedVoucherId: null,
    status: "opłacone"
  },
  {
    id: "t2",
    salonId: "demo",
    dateTime: d(0, "11:00:00"),
    clientId: "c2",
    clientName: "Katarzyna Nowak",
    staffId: "s2",
    staffName: "Aleksandra Wiśniewska",
    locationId: null,
    itemType: "usługa",
    itemCategory: "Ciało",
    itemName: "Masaż relaksacyjny 60min",
    quantity: 1,
    unitPriceBrutto: 200,
    discountAmount: 20,
    vatRate: 8,
    netAmount: 166.67,
    vatAmount: 13.33,
    grossAmount: 180,
    paymentMethod: "gotówka",
    tipAmount: 20,
    relatedVoucherId: null,
    status: "opłacone"
  },
  {
    id: "t3",
    salonId: "demo",
    dateTime: d(0, "13:30:00"),
    clientId: "c3",
    clientName: "Magdalena Wiśniewska",
    staffId: "s1",
    staffName: "Maria Kowalczyk",
    locationId: null,
    itemType: "produkt",
    itemCategory: "Kosmetyki",
    itemName: "Serum witaminowe C",
    quantity: 2,
    unitPriceBrutto: 120,
    discountAmount: 0,
    vatRate: 23,
    netAmount: 195.12,
    vatAmount: 44.88,
    grossAmount: 240,
    paymentMethod: "karta",
    tipAmount: 0,
    relatedVoucherId: null,
    status: "opłacone"
  },
  {
    id: "t4",
    salonId: "demo",
    dateTime: d(0, "15:00:00"),
    clientId: "c4",
    clientName: "Joanna Lewandowska",
    staffId: "s3",
    staffName: "Natalia Kamińska",
    locationId: null,
    itemType: "usługa",
    itemCategory: "Twarz",
    itemName: "Peeling kawitacyjny",
    quantity: 1,
    unitPriceBrutto: 150,
    discountAmount: 0,
    vatRate: 23,
    netAmount: 121.95,
    vatAmount: 28.05,
    grossAmount: 150,
    paymentMethod: "online",
    tipAmount: 15,
    relatedVoucherId: null,
    status: "opłacone"
  },
  {
    id: "t5",
    salonId: "demo",
    dateTime: d(0, "16:30:00"),
    clientId: "c5",
    clientName: "Ewa Dąbrowska",
    staffId: "s2",
    staffName: "Aleksandra Wiśniewska",
    locationId: null,
    itemType: "usługa",
    itemCategory: "Depilacja",
    itemName: "Depilacja laserowa - nogi",
    quantity: 1,
    unitPriceBrutto: 450,
    discountAmount: 50,
    vatRate: 23,
    netAmount: 325.20,
    vatAmount: 74.80,
    grossAmount: 400,
    paymentMethod: "voucher",
    tipAmount: 0,
    relatedVoucherId: "v1",
    status: "opłacone"
  },
  {
    id: "t6",
    salonId: "demo",
    dateTime: d(1, "10:00:00"),
    clientId: "c6",
    clientName: "Monika Zielińska",
    staffId: "s1",
    staffName: "Maria Kowalczyk",
    locationId: null,
    itemType: "usługa",
    itemCategory: "Twarz",
    itemName: "Oczyszczanie manualne",
    quantity: 1,
    unitPriceBrutto: 180,
    discountAmount: 0,
    vatRate: 23,
    netAmount: 146.34,
    vatAmount: 33.66,
    grossAmount: 180,
    paymentMethod: "gotówka",
    tipAmount: 20,
    relatedVoucherId: null,
    status: "opłacone"
  },
  {
    id: "t7",
    salonId: "demo",
    dateTime: d(1, "12:00:00"),
    clientId: "c7",
    clientName: "Agnieszka Szymańska",
    staffId: "s3",
    staffName: "Natalia Kamińska",
    locationId: null,
    itemType: "usługa",
    itemCategory: "Ciało",
    itemName: "Drenaż limfatyczny",
    quantity: 1,
    unitPriceBrutto: 280,
    discountAmount: 0,
    vatRate: 8,
    netAmount: 259.26,
    vatAmount: 20.74,
    grossAmount: 280,
    paymentMethod: "karta",
    tipAmount: 30,
    relatedVoucherId: null,
    status: "opłacone"
  },
  {
    id: "t8",
    salonId: "demo",
    dateTime: d(1, "14:30:00"),
    clientId: "c8",
    clientName: "Barbara Woźniak",
    staffId: "s2",
    staffName: "Aleksandra Wiśniewska",
    locationId: null,
    itemType: "produkt",
    itemCategory: "Kosmetyki",
    itemName: "Krem nawilżający premium",
    quantity: 1,
    unitPriceBrutto: 189,
    discountAmount: 0,
    vatRate: 23,
    netAmount: 153.66,
    vatAmount: 35.34,
    grossAmount: 189,
    paymentMethod: "karta",
    tipAmount: 0,
    relatedVoucherId: null,
    status: "opłacone"
  },
  {
    id: "t9",
    salonId: "demo",
    dateTime: d(2, "09:00:00"),
    clientId: "c9",
    clientName: "Dorota Kaczmarek",
    staffId: "s1",
    staffName: "Maria Kowalczyk",
    locationId: null,
    itemType: "usługa",
    itemCategory: "Twarz",
    itemName: "Lifting RF twarzy",
    quantity: 1,
    unitPriceBrutto: 500,
    discountAmount: 0,
    vatRate: 23,
    netAmount: 406.50,
    vatAmount: 93.50,
    grossAmount: 500,
    paymentMethod: "karta",
    tipAmount: 50,
    relatedVoucherId: null,
    status: "opłacone"
  },
  {
    id: "t10",
    salonId: "demo",
    dateTime: d(2, "11:30:00"),
    clientId: "c10",
    clientName: "Patrycja Piotrowska",
    staffId: "s2",
    staffName: "Aleksandra Wiśniewska",
    locationId: null,
    itemType: "usługa",
    itemCategory: "Depilacja",
    itemName: "Depilacja woskiem - bikini",
    quantity: 1,
    unitPriceBrutto: 120,
    discountAmount: 0,
    vatRate: 23,
    netAmount: 97.56,
    vatAmount: 22.44,
    grossAmount: 120,
    paymentMethod: "gotówka",
    tipAmount: 10,
    relatedVoucherId: null,
    status: "opłacone"
  }
];

export const mockDailyClosings: DailyClosing[] = [
  {
    id: "dc1",
    salonId: "demo",
    date: dd(0),
    totalServicesGross: 1080,
    totalProductsGross: 240,
    totalTips: 65,
    cashGross: 180,
    cardGross: 590,
    onlineGross: 150,
    voucherGross: 400,
    depositGross: 0,
    expectedCashInDrawer: 245,
    actualCashInDrawer: null,
    cashDifference: null,
    closedByUserId: null,
    closedByUserName: null,
    closedAt: null,
    status: "otwarte"
  },
  {
    id: "dc2",
    salonId: "demo",
    date: dd(1),
    totalServicesGross: 460,
    totalProductsGross: 189,
    totalTips: 50,
    cashGross: 200,
    cardGross: 449,
    onlineGross: 0,
    voucherGross: 0,
    depositGross: 0,
    expectedCashInDrawer: 250,
    actualCashInDrawer: 248,
    cashDifference: -2,
    closedByUserId: "u1",
    closedByUserName: "Admin",
    closedAt: d(1, "21:30:00"),
    status: "zamknięte"
  },
  {
    id: "dc3",
    salonId: "demo",
    date: dd(2),
    totalServicesGross: 620,
    totalProductsGross: 0,
    totalTips: 60,
    cashGross: 130,
    cardGross: 490,
    onlineGross: 0,
    voucherGross: 0,
    depositGross: 0,
    expectedCashInDrawer: 190,
    actualCashInDrawer: 190,
    cashDifference: 0,
    closedByUserId: "u1",
    closedByUserName: "Admin",
    closedAt: d(2, "20:45:00"),
    status: "zamknięte"
  },
  {
    id: "dc4",
    salonId: "demo",
    date: dd(3),
    totalServicesGross: 890,
    totalProductsGross: 320,
    totalTips: 85,
    cashGross: 410,
    cardGross: 680,
    onlineGross: 120,
    voucherGross: 0,
    depositGross: 0,
    expectedCashInDrawer: 495,
    actualCashInDrawer: 500,
    cashDifference: 5,
    closedByUserId: "u1",
    closedByUserName: "Admin",
    closedAt: d(3, "21:00:00"),
    status: "zamknięte"
  },
  {
    id: "dc5",
    salonId: "demo",
    date: dd(4),
    totalServicesGross: 1250,
    totalProductsGross: 156,
    totalTips: 120,
    cashGross: 520,
    cardGross: 756,
    onlineGross: 130,
    voucherGross: 0,
    depositGross: 0,
    expectedCashInDrawer: 640,
    actualCashInDrawer: 635,
    cashDifference: -5,
    closedByUserId: "u1",
    closedByUserName: "Admin",
    closedAt: d(4, "21:15:00"),
    status: "zamknięte"
  }
];

export const mockEmployeeCommissions: EmployeeCommission[] = [
  {
    id: "ec1",
    salonId: "demo",
    staffId: "s1",
    staffName: "Maria Kowalczyk",
    staffAvatar: null,
    periodStart: dd(30),
    periodEnd: dd(0),
    servicesGross: 4850,
    productsGross: 720,
    tipsTotal: 280,
    commissionServices: 1455,
    commissionProducts: 72,
    totalCommission: 1527,
    totalPayout: 1807
  },
  {
    id: "ec2",
    salonId: "demo",
    staffId: "s2",
    staffName: "Aleksandra Wiśniewska",
    staffAvatar: null,
    periodStart: dd(30),
    periodEnd: dd(0),
    servicesGross: 3920,
    productsGross: 580,
    tipsTotal: 195,
    commissionServices: 1176,
    commissionProducts: 58,
    totalCommission: 1234,
    totalPayout: 1429
  },
  {
    id: "ec3",
    salonId: "demo",
    staffId: "s3",
    staffName: "Natalia Kamińska",
    staffAvatar: null,
    periodStart: dd(30),
    periodEnd: dd(0),
    servicesGross: 2680,
    productsGross: 245,
    tipsTotal: 145,
    commissionServices: 804,
    commissionProducts: 24.5,
    totalCommission: 828.5,
    totalPayout: 973.5
  }
];

export const mockVouchers: Voucher[] = [
  {
    id: "v1",
    salonId: "demo",
    code: "GIFT-2024-001",
    type: "voucher kwotowy",
    clientId: "c5",
    clientName: "Ewa Dąbrowska",
    issueDate: dd(10),
    expiryDate: dd(-180),
    originalValue: 500,
    remainingValue: 100,
    currency: "PLN",
    status: "aktywny"
  },
  {
    id: "v2",
    salonId: "demo",
    code: "BIRTH-2024-012",
    type: "voucher kwotowy",
    clientId: "c2",
    clientName: "Katarzyna Nowak",
    issueDate: dd(30),
    expiryDate: dd(-20),
    originalValue: 300,
    remainingValue: 300,
    currency: "PLN",
    status: "aktywny"
  },
  {
    id: "v3",
    salonId: "demo",
    code: "PKG-FACE-001",
    type: "pakiet",
    clientId: "c1",
    clientName: "Anna Kowalska",
    issueDate: dd(5),
    expiryDate: dd(-85),
    originalValue: 1200,
    remainingValue: 800,
    currency: "PLN",
    status: "aktywny"
  },
  {
    id: "v4",
    salonId: "demo",
    code: "VZ-MEZO-005",
    type: "voucher zabiegowy",
    clientId: "c3",
    clientName: "Magdalena Wiśniewska",
    issueDate: dd(90),
    expiryDate: dd(5),
    originalValue: 350,
    remainingValue: 0,
    currency: "PLN",
    status: "wykorzystany"
  },
  {
    id: "v5",
    salonId: "demo",
    code: "PROMO-2023-099",
    type: "voucher kwotowy",
    clientId: "c8",
    clientName: "Barbara Woźniak",
    issueDate: dd(120),
    expiryDate: dd(15),
    originalValue: 200,
    remainingValue: 150,
    currency: "PLN",
    status: "wygasły"
  },
  {
    id: "v6",
    salonId: "demo",
    code: "PKG-BODY-003",
    type: "pakiet",
    clientId: "c6",
    clientName: "Monika Zielińska",
    issueDate: dd(7),
    expiryDate: dd(-175),
    originalValue: 1500,
    remainingValue: 1500,
    currency: "PLN",
    status: "aktywny"
  }
];

export const mockAccountingExports: AccountingExport[] = [
  {
    id: "ae1",
    salonId: "demo",
    generatedByUserId: "u1",
    generatedByUserName: "Admin",
    generatedAt: d(1, "18:30:00"),
    periodStart: dd(14),
    periodEnd: dd(1),
    type: "sprzedaż VAT",
    format: "csv",
    targetEmail: "ksiegowosc@salon.pl",
    downloadUrl: "#"
  },
  {
    id: "ae2",
    salonId: "demo",
    generatedByUserId: "u1",
    generatedByUserName: "Admin",
    generatedAt: d(5, "12:00:00"),
    periodStart: dd(15),
    periodEnd: dd(5),
    type: "prowizje",
    format: "xlsx",
    targetEmail: null,
    downloadUrl: "#"
  },
  {
    id: "ae3",
    salonId: "demo",
    generatedByUserId: "u1",
    generatedByUserName: "Admin",
    generatedAt: d(30, "09:00:00"),
    periodStart: dd(60),
    periodEnd: dd(30),
    type: "pełny",
    format: "csv",
    targetEmail: "ksiegowosc@salon.pl",
    downloadUrl: "#"
  }
];
