import { Zap, Sparkles, Crown } from "lucide-react";

export const getPlans = (isAnnual: boolean) => [
  {
    name: "STARTER",
    price: isAnnual ? "15 zł" : "19 zł",
    period: "/ miesiąc",
    description: "Dla jednoosobowych salonów, które chcą porządek w rezerwacjach",
    features: [
      "Max 1 pracownik",
      "Max 100 klientek w bazie",
      "Max 21 usług",
      "Max 21 produktów w magazynie",
      "Powiadomienia email + SMS",
      "Kalendarz + Widget rezerwacji",
      "Podstawowe statystyki",
    ],
    limitations: [
      "Aplikacja mobilna",
      "Ścieżka Klientki™",
      "Program poleceń",
      "AI Autopilot",
      "Raporty finansowe",
    ],
    cta: "Wybierz Starter",
    ctaLink: "/auth",
    popular: false,
    icon: Zap,
    savings: isAnnual ? "Oszczędzasz 48 zł/rok" : undefined,
  },
  {
    name: "PRO",
    price: isAnnual ? "79 zł" : "99 zł",
    period: "/ miesiąc",
    description: "Pełna platforma dla salonów, które chcą rosnąć i odzyskać kontrolę",
    features: [
      "Wszystko ze STARTER +",
      "Nieograniczeni pracownicy",
      "Nieograniczone usługi i klientki",
      "Nieograniczony magazyn",
      "Aplikacja mobilna (właściciel + klientka)",
      "Ścieżka Klientki™ (ręczna konfiguracja)",
      "Program poleceń",
      "Karty konsultacyjne",
      "Eksport danych + raporty finansowe",
      "Receptury i True Profit",
      "Skanowanie kodów kamerą",
    ],
    limitations: [
      "AI Autopilot",
      "AI Segmentacja",
      "AI Prognoza przychodów",
      "Onboarding 1:1",
    ],
    cta: "Wybierz Pro",
    ctaLink: "/auth",
    popular: true,
    icon: Sparkles,
    savings: isAnnual ? "Oszczędzasz 240 zł/rok" : undefined,
  },
  {
    name: "ELITE",
    price: isAnnual ? "279 zł" : "349 zł",
    setupFee: true,
    setupPrice: "497 zł",
    period: "/ miesiąc",
    badge: "Pełna moc",
    description: "System, który pracuje za Ciebie 24/7 — konfigurujemy wszystko za Ciebie",
    features: [
      "Wszystko z PRO +",
      "🤖 AI Autopilot (wykrywa, wysyła, reaguje)",
      "AI Segmentacja klientek automatyczna",
      "AI Prognoza przychodów (30 dni)",
      "Radar Odejść (wykrywa zagrożone klientki)",
      "AI sugestie najlepszych terminów",
      "Prywatny Onboarding Call 1:1",
      "Konfiguracja sekwencji za Ciebie",
      "Konsultacja strategiczna salonu",
      "Sprawdzone metody pozyskiwania klientów",
      "Priorytetowy support — odpowiedź w 2h",
    ],
    cta: "Wybierz Elite",
    ctaLink: "/auth",
    popular: false,
    icon: Crown,
    savings: isAnnual ? "Oszczędzasz 840 zł/rok" : undefined,
  },
];
