import { Zap, Sparkles, Crown } from "lucide-react";
import { TFunction } from "i18next";

export const getPlans = (isAnnual: boolean, t: TFunction) => [
  {
    name: t("landing.pricing.starterName"),
    price: isAnnual ? "15 zł" : "19 zł",
    period: "/ miesiąc",
    description: t("landing.pricing.starterDesc"),
    features: [
      t("landing.pricing.f_1worker"),
      t("landing.pricing.f_100clients"),
      t("landing.pricing.f_21services"),
      t("landing.pricing.f_21products"),
      t("landing.pricing.f_notifications"),
      t("landing.pricing.f_calendar"),
      t("landing.pricing.f_basicStats"),
    ],
    limitations: [
      t("landing.pricing.l_mobileApp"),
      t("landing.pricing.l_clientPath"),
      t("landing.pricing.l_referral"),
      t("landing.pricing.l_autopilot"),
      t("landing.pricing.l_reports"),
    ],
    cta: t("landing.pricing.starterCta"),
    ctaLink: "/auth",
    popular: false,
    icon: Zap,
    savings: isAnnual ? t("landing.pricing.savingsStarter") : undefined,
  },
  {
    name: t("landing.pricing.proName"),
    price: isAnnual ? "79 zł" : "99 zł",
    period: "/ miesiąc",
    description: t("landing.pricing.proDesc"),
    features: [
      t("landing.pricing.f_allStarter"),
      t("landing.pricing.f_unlimitedStaff"),
      t("landing.pricing.f_unlimitedServices"),
      t("landing.pricing.f_unlimitedStock"),
      t("landing.pricing.f_mobileApp"),
      t("landing.pricing.f_clientPath"),
      t("landing.pricing.f_referral"),
      t("landing.pricing.f_consultCards"),
      t("landing.pricing.f_exportReports"),
      t("landing.pricing.f_trueProfit"),
      t("landing.pricing.f_barcodeScanning"),
    ],
    limitations: [
      t("landing.pricing.l_aiAutopilot"),
      t("landing.pricing.l_aiSegmentation"),
      t("landing.pricing.l_aiRevenue"),
      t("landing.pricing.l_onboarding"),
    ],
    cta: t("landing.pricing.proCta"),
    ctaLink: "/auth",
    popular: true,
    icon: Sparkles,
    savings: isAnnual ? t("landing.pricing.savingsPro") : undefined,
  },
  {
    name: t("landing.pricing.eliteName"),
    price: isAnnual ? "279 zł" : "349 zł",
    setupFee: true,
    setupPrice: "497 zł",
    period: "/ miesiąc",
    badge: t("landing.pricing.eliteBadge"),
    description: t("landing.pricing.eliteDesc"),
    features: [
      t("landing.pricing.f_allPro"),
      t("landing.pricing.f_autopilot"),
      t("landing.pricing.f_aiSegmentation"),
      t("landing.pricing.f_aiRevenue"),
      t("landing.pricing.f_churnRadar"),
      t("landing.pricing.f_aiSlots"),
      t("landing.pricing.f_onboarding"),
      t("landing.pricing.f_sequenceSetup"),
      t("landing.pricing.f_strategy"),
      t("landing.pricing.f_acquisition"),
      t("landing.pricing.f_prioritySupport"),
    ],
    cta: t("landing.pricing.eliteCta"),
    ctaLink: "/auth",
    popular: false,
    icon: Crown,
    savings: isAnnual ? t("landing.pricing.savingsElite") : undefined,
  },
];
